config/routes.rb
Rails.application.routes.draw do
  resources :kittens
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "kittens#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/kitten.rb
class Kitten < ApplicationRecord
  validates :name, :age, :softness, :cuteness, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  before_action :set_kitten, only: %i[ show edit update destroy ]

  def index
    @kittens = Kitten.all
    respond_to do |format|
      format.html
      format.json {render json: @kittens }
    end
  end

  def show
    set_kitten
    respond_to do |format|
      format.html
      format.json {render json: set_kitten }
    end
  end

  def new
    @kitten = Kitten.new
  end

  def edit
  end

  def create
    @kitten = Kitten.new(kitten_params)
    if @kitten.save
      flash[:notice] = "Your kitten was successfully created."
      redirect_to kitten_url(@kitten)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @kitten.update(kitten_params)
      flash[:notice] = "Your kitten was successfully updated."
      redirect_to kitten_url(@kitten)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @kitten.destroy

    flash[:notice] = "Your kitten was successfully destroyed."
    redirect_to kittens_url
  end


  private

  def set_kitten
    @kitten = Kitten.find(params[:id])
  end

  def kitten_params
    params.require(:kitten).permit(:name, :age, :cuteness, :softness)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_form.html.erb
<%= form_with(model: kitten) do |form| %>
  <% if kitten.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(kitten.errors.count, "error") %> prohibited this kitten from being saved:</h2>

      <ul>
        <% kitten.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col">
      <%= form.label :name, style: "display: block" %>
      <%= form.text_field :name, class: "form-control" %>
    </div>
    <div class="col">
      <%= form.label :age, style: "display: block" %>
      <%= form.text_field :age, class: "form-control" %>
    </div>
  </div>
  <div class="row">
    <div class="col">
     <%= form.label :cuteness, style: "display: block" %>
     <%= form.text_field :cuteness, class: "form-control" %>
   </div>
   <div class="col">
     <%= form.label :softness, style: "display: block" %>
     <%= form.text_field :softness, class: "form-control" %>
   </div>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/kittens/_kitten.html.erb
<div>
  <p>
    <strong>Name:</strong>
    <%= kitten.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= kitten.age %>
  </p>

  <p>
    <strong>Age:</strong>
    <%= kitten.cuteness %>
  </p>

  <p>
    <strong>Age:</strong>
    <%= kitten.softness %>
  </p>
</div>

app/views/kittens/edit.html.erb
<h1>Edit Kitten</h1>

<%= render "form", kitten: @kitten %>

<br>

<div>
  <%= link_to "Show this kitten", @kitten %> |
  <%= link_to "Back to kittens", kittens_path %>
</div>

app/views/kittens/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>List of all The Kittens</h1>

<div>
  <% @kittens.each do |kitten| %>
  <div class="card" style="width: 18rem;">
    <div class="card-header text-center">
      <strong><%= kitten.name %></strong>
    </div>
    <div class="list-group text-center" >
      Age: <%= kitten.age %>
    </div>
  </div>
    <p>
      <%= link_to "Show this kitten", kitten %>
    </p>
  <% end %>
</div>

<%= link_to "Add kitten to list", new_kitten_path %>

app/views/kittens/new.html.erb
<h1>Create a Kitten</h1>

<%= render "form", kitten: @kitten %>

<br>

<div>
  <%= link_to "Back to kittens list", kittens_path %>
</div>

app/views/kittens/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @kitten %>

<div>
  <%= link_to "Edit this kitten", edit_kitten_path(@kitten) %> |
  <%= link_to "Back to kittens", kittens_path %>

  <%= button_to "Destroy this kitten", @kitten, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KittensApi</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
    <div class="container-fluid">
      <%= yield %>
    </div>
  </body>
</html>